x-dev_image_base: &dev_image_base
  build: 
    context: .
    dockerfile: Dockerfile.development

x-frontend_base: &frontend_base
  <<: *dev_image_base
  volumes: 
    - .:/src
    - frontend_node_modules:/src/node_modules

x-backend_base: &backend_base
  <<: *dev_image_base
  working_dir: /src/server
  volumes:
    - .:/src
    - backend_node_modules:/src/server/node_modules

services:
  install-web:
    <<: *frontend_base
    command: npm i
  install-backend:
    <<: *backend_base
    command: npm i
  web:
    <<: *frontend_base
    command: ng serve --host 0.0.0.0
    ports:
      - "4200:4200"
    depends_on:
      install-web:
        condition: service_completed_successfully
  backend:
    <<: *backend_base
    command: npm run server:dev
    ports:
      - "3001:3000"
    networks:
      backend:
    env_file:
      - config/backend.env
    depends_on:
      install-backend:
        condition: service_completed_successfully
  database:
    ports:
      - "3002:27017"

volumes:
  backend_node_modules:
  frontend_node_modules: