version: "3.9"
services:
  web:
    # TODO: add healthcheck
    build: .
    ports:
      - "80:3000"
    networks:
      - backend
      - frontend
    volumes:
      - /spendit/node_modules
    restart: unless-stopped
  database:
    # TODO: add healthcheck
    image: mongo:6
    restart: unless-stopped
    volumes: 
      - data/db:/data/db
    networks:
      backend:

networks:
  backend:
  frontend: