version: "3.9"
services:
  web:
    # TODO: add healthcheck
    build:
      context: .
      args:
        jwt_secret: "${JWT_SECRET}"
        admin_password: "${ADMIN_PASSWORD}"
    ports:
      - "3000:3000"
    networks:
      - backend
    volumes:
      - /spendit/node_modules
    restart: unless-stopped
  database:
    # TODO: add healthcheck
    image: mongo:6
    restart: unless-stopped
    user: "mongodb:mongodb"
    envfile:
      - config/backend.env
    volumes: 
      - ./data:/data:Z
    networks:
      - backend

networks:
  backend: