version: "3.9"
services:
  web:
    # TODO: add healthcheck
    build:
      context: .
      args:
        jwt_secret: "${JWT_SECRET}"
        admin_password: "${ADMIN_PASSWORD}"
    networks:
      backend:
      frontend:
        aliases:
          - web
    volumes:
      - /spendit/node_modules
    restart: unless-stopped
  database:
    # TODO: add healthcheck
    image: mongo:6
    restart: unless-stopped
    volumes: 
      - ./data:/data:Z
    networks:
      backend:
        aliases:
          - database
  proxy:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    restart: unless-stopped
    volumes:
      - ./config/nginx.conf:/etc/nginx/nginx.conf
      - ./config/ssl:/ssl
    networks:
      - frontend

networks:
  backend:
  frontend: