version: "3.9"
services:
  web:
    build: .
    ports:
      - "3001:3000"
    networks:
      - backend
      - frontend
    volumes:
      - /spendit/node_modules
  database:
    # need to add mongodata for data storage
    image: mongo:6
    ports:
      - "3002:27017"
    networks:
      backend:

networks:
  backend:
  frontend:

volumes:
  mongodata: