services:
  frontend:
    image: ghcr.io/jac4e/spendit:main
    ports:
      - "8080:80"
    depends_on:
      - backend
    environment:
      BACKEND_URL: https://localhost:3443
      API_BASE_URL: https://localhost:3443/api
      STRIPE_PUBLIC_KEY: pk_test_123
      BRAND_NAME: spendit
      BRAND_EMAIL: hello@spendit.dev
      PRIMARY_COLOR: 000000
      SECONDARY_COLOR: 000000
      LOGO_URL: logo
  backend:
    image: ghcr.io/jac4e/serveit:main
    networks:
      - backend
    ports:
      - "3443:3443"
    depends_on:
      - database
    restart: unless-stopped
    environment:
      NODE_ENV: "development"       # set to "production" or "development"
      DB_URL: "database"
      DB_PORT: "27017"
      INCLUDE_APP: "false"
      INCLUDE_GOOGLE: "false"         # whether the backend server should use google services (true/false)
      BACKEND_PORT: "3443"           # port to run backend server on
      BACKEND_DOMAIN: "localhost"  # domain to run backend server on
      #CF_TOKEN: "<cloudflare token>" # cloudflare api token
      #STRIPE_SECRET: "<stripe secret key>"
      #STRIPE_WEBHOOK_SECRET: "<stripe webhook secret key>"
  database:
    image: mongo:6
    restart: unless-stopped
    # Uncomment if you want to access using compass
    # ports:
    #   - "27017:27017"
    volumes: 
      - database_data:/data/db
    networks:
      - backend

volumes:
  database_data:


networks:
  backend: